'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown, CheckCircle2, AlertCircle } from 'lucide-react';
import { cn } from '@/lib/utils/cn';
import type { SectionResult } from '@/types/consultation';

interface SectionScoreProps {
  title: string;
  result: SectionResult;
  index: number;
  icon: React.ReactNode;
}

function getLabelColor(label: string): string {
  switch (label) {
    case 'Excellent': return 'text-emerald-400 bg-emerald-500/10 border-emerald-500/20';
    case 'Good': return 'text-blue-400 bg-blue-500/10 border-blue-500/20';
    case 'Average': return 'text-amber-400 bg-amber-500/10 border-amber-500/20';
    case 'Poor': return 'text-red-400 bg-red-500/10 border-red-500/20';
    default: return 'text-[#9090a8] bg-[#1c1c26] border-[#2a2a38]';
  }
}

function getProgressColor(pct: number): string {
  if (pct >= 80) return 'bg-emerald-500';
  if (pct >= 60) return 'bg-blue-500';
  if (pct >= 40) return 'bg-amber-500';
  return 'bg-red-500';
}

function renderInlineBold(text: string): React.ReactNode {
  const parts = text.split(/(\*\*.*?\*\*)/g);
  return (
    <>
      {parts.map((part, i) =>
        part.startsWith('**') && part.endsWith('**') && part.length > 4
          ? <strong key={i} className="text-[#d8d8f0] font-semibold">{part.slice(2, -2)}</strong>
          : <span key={i}>{part}</span>
      )}
    </>
  );
}

function BulletContent({ text }: { text: string }) {
  // Split on " - **" which marks inline bullet items generated by the rubric
  const parts = text.split(/ - (?=\*\*)/);
  return (
    <div className="space-y-2">
      {parts.map((part, i) => {
        const trimmed = part.trim();
        if (!trimmed) return null;
        if (i === 0) {
          return (
            <p key={i} className="text-base text-[#9090a8] leading-relaxed">
              {renderInlineBold(trimmed)}
            </p>
          );
        }
        return (
          <div key={i} className="flex items-start gap-2 pl-1">
            <span className="text-indigo-400/60 mt-1.5 shrink-0 text-[8px]">◆</span>
            <p className="text-sm text-[#9090a8] leading-relaxed">
              {renderInlineBold(trimmed)}
            </p>
          </div>
        );
      })}
    </div>
  );
}

function FeedbackContent({ text }: { text: string }) {
  // Split into sections at "Part N —" markers
  const sections = text.split(/(?=Part\s+\d+\s*[—–-])/i);
  return (
    <div className="space-y-4">
      {sections.map((section, si) => {
        const trimmed = section.trim();
        if (!trimmed) return null;

        const partMatch = trimmed.match(/^Part\s+\d+\s*[—–-]\s*([\s\S]*)/i);
        if (partMatch) {
          const rest = partMatch[1];
          const colonIdx = rest.indexOf(':');
          const header = colonIdx > 0 && colonIdx < 60 ? rest.slice(0, colonIdx).trim() : 'Guidance';
          const body = colonIdx > 0 && colonIdx < 60 ? rest.slice(colonIdx + 1).trim() : rest.trim();
          return (
            <div key={si} className="space-y-2">
              <p className="text-xs font-bold text-indigo-300 uppercase tracking-widest pb-1 border-b border-indigo-500/20">
                {header}
              </p>
              <BulletContent text={body} />
            </div>
          );
        }

        return <BulletContent key={si} text={trimmed} />;
      })}
    </div>
  );
}

export function SectionScore({ title, result, index, icon }: SectionScoreProps) {
  const [expanded, setExpanded] = useState(true);
  const pct = Math.round((result.score / result.max_score) * 100);

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.1, duration: 0.4, ease: [0.22, 1, 0.36, 1] }}
      className="rounded-xl border border-[#2a2a38] bg-[#13131a] overflow-hidden"
    >
      {/* Clickable header — toggles expand/collapse */}
      <button
        onClick={() => setExpanded(v => !v)}
        className="w-full flex items-center justify-between px-5 py-4 hover:bg-[#1a1a24] transition-colors text-left"
      >
        <div className="flex items-center gap-3 min-w-0">
          <div className="w-8 h-8 rounded-lg bg-[#1c1c26] border border-[#2a2a38] flex items-center justify-center text-[#9090a8] shrink-0">
            {icon}
          </div>
          <div className="min-w-0">
            <h3 className="font-semibold text-[#f1f1f5] text-lg">{title}</h3>
            <span className={cn('inline-flex items-center rounded border px-1.5 py-px text-xs font-medium mt-0.5', getLabelColor(result.label))}>
              {result.label}
            </span>
          </div>
        </div>
        <div className="flex items-center gap-3 shrink-0 ml-3">
          <div className="text-right">
            <span className="text-xl font-bold text-[#f1f1f5]">{result.score.toFixed(0)}</span>
            <span className="text-xs text-[#60607a]">/{result.max_score}</span>
          </div>
          <ChevronDown
            className={cn('h-4 w-4 text-[#60607a] transition-transform duration-200', expanded && 'rotate-180')}
          />
        </div>
      </button>

      {/* Score progress bar — always visible */}
      <div className="px-5">
        <div className="h-[3px] rounded-full bg-[#1c1c26] overflow-hidden">
          <motion.div
            className={cn('h-full rounded-full', getProgressColor(pct))}
            initial={{ width: 0 }}
            animate={{ width: `${pct}%` }}
            transition={{ duration: 1, delay: index * 0.1 + 0.3, ease: 'easeOut' }}
          />
        </div>
      </div>

      {/* Collapsible body */}
      <AnimatePresence initial={false}>
        {expanded && (
          <motion.div
            key="body"
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.28, ease: [0.22, 1, 0.36, 1] }}
            className="overflow-hidden"
          >
            <div className="px-5 pb-5 pt-4 space-y-4">

              {/* Strengths — green cards */}
              {result.strengths.length > 0 && (
                <div>
                  <p className="text-sm font-bold text-emerald-400 uppercase tracking-widest mb-2.5">
                    What You Did Well
                  </p>
                  <div className="space-y-2">
                    {result.strengths.map((s, i) => (
                      <div
                        key={i}
                        className="flex items-start gap-2.5 rounded-lg bg-emerald-500/5 border border-emerald-500/15 px-3 py-2.5"
                      >
                        <CheckCircle2 className="h-4 w-4 text-emerald-400 shrink-0 mt-0.5" />
                        <p className="text-base text-emerald-200/80 leading-relaxed">{s}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Missed opportunities — amber cards */}
              {result.missed_opportunities.length > 0 && (
                <div>
                  <p className="text-sm font-bold text-amber-400 uppercase tracking-widest mb-2.5">
                    Missed Opportunities
                  </p>
                  <div className="space-y-2">
                    {result.missed_opportunities.map((m, i) => (
                      <div
                        key={i}
                        className="flex items-start gap-2.5 rounded-lg bg-amber-500/5 border border-amber-500/15 px-3 py-2.5"
                      >
                        <AlertCircle className="h-4 w-4 text-amber-400 shrink-0 mt-0.5" />
                        <p className="text-base text-amber-200/80 leading-relaxed">{m}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Coach's feedback — structured, point-wise */}
              {result.feedback && (
                <div>
                  <p className="text-sm font-bold text-indigo-400 uppercase tracking-widest mb-2.5">
                    Coach&apos;s Guidance
                  </p>
                  <div className="rounded-lg bg-[#15152a] border border-indigo-500/20 px-4 py-3.5">
                    <FeedbackContent text={result.feedback} />
                  </div>
                </div>
              )}

            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}
